version: "3"
services:
  app:
    build:
      context: ..
      target: builder
    ports:
      - "3030:3000"
    volumes:
      - ../:/app
    command: air
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  db-data:
